# on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize West and Update Modules
        run: |
          west init -l config
          west update
          west zephyr-export
          pip3 install --user -r zmk/zephyr/scripts/requirements.txt

      - name: Build Firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=config -DSHIELD="sofle_left nice_view_adapter nice_view"

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
